#!/bin/bash

BIN=$1

if ! test -e exome_v1_male_$BIN ; then
	mkdir exome_v1_male_$BIN
fi

if ! test -e exome_v1_male_$BIN/targets.bed ; then
	qrun "R=2 C=1 P=2 G=cnvkit" cnvkit.py target /mnt/Data2/exome_sequencing/resources/v1/variantcall.bed --split -o exome_v1_male_$BIN/targets.bed
fi
if ! test -e exome_v1_male_$BIN/access.bed ; then
	qrun "R=2 C=1 P=2 G=cnvkit" cnvkit.py access /mnt/Data1/resources/human_g1k_v37.fasta -o exome_v1_male_$BIN/access.bed
fi
if ! test -e exome_v1_male_$BIN/antitargets.bed ; then
	qrun "R=2 C=1 P=2 G=cnvkit" cnvkit.py antitarget exome_v1_male_$BIN/targets.bed -g exome_v1_male_$BIN/access.bed -a $BIN -o exome_v1_male_$BIN/antitargets.bed
fi

if ! test -e exome_v1_male_$BIN/targets ; then
	mkdir exome_v1_male_$BIN/targets
	mkdir exome_v1_male_$BIN/antitargets
	for BAM in /mnt/Data6/mw501/papers/2017_1_off_target_reads/exomes/v1/male/*.bam ; do
		OUT=`echo $BAM | sed -e "s/^.*\///;s/\.bam$//"`
		qrun "R=2 C=2 P=2 G=cnvkit" cnvkit.py coverage $BAM exome_v1_male_$BIN/targets.bed -o exome_v1_male_$BIN/targets/${OUT}.cnn &
	done
	wait
	for BAM in /mnt/Data6/mw501/papers/2017_1_off_target_reads/exomes/v1/male/*.bam ; do
		OUT=`echo $BAM | sed -e "s/^.*\///;s/\.bam$//"`
		qrun "R=2 C=2 P=2 G=cnvkit" cnvkit.py coverage $BAM exome_v1_male_$BIN/antitargets.bed -o exome_v1_male_$BIN/antitargets/${OUT}.cnn &
	done
	wait
fi

if ! test -e exome_v1_male_$BIN/reference.cnn ; then
	qrun "R=2 C=2 P=2 G=cnvkit" cnvkit.py reference -g male exome_v1_male_$BIN/targets/*.cnn exome_v1_male_$BIN/antitargets/*.cnn -f /mnt/Data1/resources/human_g1k_v37.fasta -o exome_v1_male_$BIN/reference.cnn
fi

if ! test -e exome_v1_male_$BIN/fix ; then
	mkdir exome_v1_male_$BIN/fix
	for BAM in /mnt/Data6/mw501/papers/2017_1_off_target_reads/exomes/v1/male/*.bam ; do
		OUT=`echo $BAM | sed -e "s/^.*\///;s/\.bam$//"`
		qrun "R=2 C=2 P=2 G=cnvkit" cnvkit.py fix exome_v1_male_$BIN/targets/${OUT}.cnn exome_v1_male_$BIN/antitargets/${OUT}.cnn exome_v1_male_$BIN/reference.cnn -o exome_v1_male_$BIN/fix/${OUT}.fix.cnr &
	done
	wait
fi

if ! test -e exome_v1_male_$BIN/segment ; then
	mkdir exome_v1_male_$BIN/segment
	for BAM in /mnt/Data6/mw501/papers/2017_1_off_target_reads/exomes/v1/male/*.bam ; do
		OUT=`echo $BAM | sed -e "s/^.*\///;s/\.bam$//"`
		qrun "R=2 C=2 P=2 G=cnvkit" cnvkit.py segment -m haar exome_v1_male_$BIN/fix/${OUT}.fix.cnr -o exome_v1_male_$BIN/segment/${OUT}.cns &
	done
	wait
fi

if ! test -e exome_v1_male_$BIN/call ; then
	mkdir exome_v1_male_$BIN/call
	for BAM in /mnt/Data6/mw501/papers/2017_1_off_target_reads/exomes/v1/male/*.bam ; do
		OUT=`echo $BAM | sed -e "s/^.*\///;s/\.bam$//"`
		qrun "R=2 C=1 P=2 G=cnvkit" cnvkit.py call -g male exome_v1_male_$BIN/segment/${OUT}.cns -o exome_v1_male_$BIN/call/${OUT}.cns &
	done
	wait
fi

if ! test -e exome_v1_male_$BIN/results ; then
	mkdir exome_v1_male_$BIN/results
	for BAM in /mnt/Data6/mw501/papers/2017_1_off_target_reads/exomes/v1/male/*.bam ; do
		OUT=`echo $BAM | sed -e "s/^.*\///;s/\.bam$//"`
		grep "^chromosome\|^[1-9].*	[^2]	[0-9.]*	[0-9]*	[0-9.]*$\|^X.*	[^1]	[0-9.]*	[0-9]*	[0-9.]*$" <exome_v1_male_$BIN/call/${OUT}.cns >exome_v1_male_$BIN/results/${OUT}.results
	done
fi


