#!/bin/bash

BIN=$1

if ! test -e tngsv501_female_$BIN ; then
	mkdir tngsv501_female_$BIN
fi

if ! test -e tngsv501_female_$BIN/targets.bed ; then
	qrun "R=2 C=1 P=2 G=cnvkit" cnvkit.py target /mnt/Data6/mw501/papers/2017_1_off_target_reads/genomes/v501_all_variant_calling_sorted.bed --split -o tngsv501_female_$BIN/targets.bed
fi
if ! test -e tngsv501_female_$BIN/access.bed ; then
	qrun "R=2 C=1 P=2 G=cnvkit" cnvkit.py access /mnt/Data1/resources/human_g1k_v37.fasta -o tngsv501_female_$BIN/access.bed
fi
if ! test -e tngsv501_female_$BIN/antitargets.bed ; then
	qrun "R=2 C=1 P=2 G=cnvkit" cnvkit.py antitarget tngsv501_female_$BIN/targets.bed -g tngsv501_female_$BIN/access.bed -a $BIN -o tngsv501_female_$BIN/antitargets.bed
fi

if ! test -e tngsv501_female_$BIN/targets ; then
	mkdir tngsv501_female_$BIN/targets
	mkdir tngsv501_female_$BIN/antitargets
	for BAM in /mnt/Data6/mw501/papers/2017_1_off_target_reads/genomes/v501/female/*.bam ; do
		OUT=`echo $BAM | sed -e "s/^.*\///;s/\.bam$//"`
		qrun "R=2 C=2 P=2 G=cnvkit" cnvkit.py coverage $BAM tngsv501_female_$BIN/targets.bed -o tngsv501_female_$BIN/targets/${OUT}.cnn &
	done
	wait
	for BAM in /mnt/Data6/mw501/papers/2017_1_off_target_reads/genomes/v501/female/*.bam ; do
		OUT=`echo $BAM | sed -e "s/^.*\///;s/\.bam$//"`
		qrun "R=2 C=2 P=2 G=cnvkit" cnvkit.py coverage $BAM tngsv501_female_$BIN/antitargets.bed -o tngsv501_female_$BIN/antitargets/${OUT}.cnn &
	done
	wait
fi

if ! test -e tngsv501_female_$BIN/reference.cnn ; then
	qrun "R=2 C=2 P=2 G=cnvkit" cnvkit.py reference -g female tngsv501_female_$BIN/targets/*.cnn tngsv501_female_$BIN/antitargets/*.cnn -f /mnt/Data1/resources/human_g1k_v37.fasta -o tngsv501_female_$BIN/reference.cnn
fi

if ! test -e tngsv501_female_$BIN/fix ; then
	mkdir tngsv501_female_$BIN/fix
	for BAM in /mnt/Data6/mw501/papers/2017_1_off_target_reads/genomes/v501/female/*.bam ; do
		OUT=`echo $BAM | sed -e "s/^.*\///;s/\.bam$//"`
		qrun "R=2 C=2 P=2 G=cnvkit" cnvkit.py fix tngsv501_female_$BIN/targets/${OUT}.cnn tngsv501_female_$BIN/antitargets/${OUT}.cnn tngsv501_female_$BIN/reference.cnn -o tngsv501_female_$BIN/fix/${OUT}.fix.cnr &
	done
	wait
fi

if ! test -e tngsv501_female_$BIN/segment ; then
	mkdir tngsv501_female_$BIN/segment
	for BAM in /mnt/Data6/mw501/papers/2017_1_off_target_reads/genomes/v501/female/*.bam ; do
		OUT=`echo $BAM | sed -e "s/^.*\///;s/\.bam$//"`
		qrun "R=2 C=2 P=2 G=cnvkit" cnvkit.py segment -m haar tngsv501_female_$BIN/fix/${OUT}.fix.cnr -o tngsv501_female_$BIN/segment/${OUT}.cns &
	done
	wait
fi

if ! test -e tngsv501_female_$BIN/call ; then
	mkdir tngsv501_female_$BIN/call
	for BAM in /mnt/Data6/mw501/papers/2017_1_off_target_reads/genomes/v501/female/*.bam ; do
		OUT=`echo $BAM | sed -e "s/^.*\///;s/\.bam$//"`
		qrun "R=2 C=1 P=2 G=cnvkit" cnvkit.py call -g female tngsv501_female_$BIN/segment/${OUT}.cns -o tngsv501_female_$BIN/call/${OUT}.cns &
	done
	wait
fi

if ! test -e tngsv501_female_$BIN/results ; then
	mkdir tngsv501_female_$BIN/results
	for BAM in /mnt/Data6/mw501/papers/2017_1_off_target_reads/genomes/v501/female/*.bam ; do
		OUT=`echo $BAM | sed -e "s/^.*\///;s/\.bam$//"`
		grep "^chromosome\|^[1-9X].*	[^2]	[0-9.]*	[0-9]*	[0-9.]*$" <tngsv501_female_$BIN/call/${OUT}.cns >tngsv501_female_$BIN/results/${OUT}.results
	done
fi


