#!/bin/bash

for BIN in 50 100 200 500 1000 2000 ; do
	awk '{ if ($9 > 0.3) print }' <copywriter/results_$BIN | java -Xmx10g AnalyseCnvs /dev/stdin -truth tngs_truth.txt -copywriter -optimise 6 -optimise 9 -optimise 10 | sed -e "s/$/\t$BIN/" >copywriter/analyse_$BIN
	awk '{ if ($9 > 0.3) print }' <copywriter/results_$BIN | java -Xmx10g AnalyseCnvs /dev/stdin -truth tngs_truth_large.txt -copywriter -optimise 6 -optimise 9 -optimise 10 | sed -e "s/$/\t$BIN/" >copywriter/large_analyse_$BIN
	awk '{ if ($9 > 0.3) print }' <copywriter/results_$BIN | java -Xmx10g AnalyseCnvs /dev/stdin -truth tngs_truth_xlarge.txt -copywriter -optimise 6 -optimise 9 -optimise 10 | sed -e "s/$/\t$BIN/" >copywriter/xlarge_analyse_$BIN
done
